[package]
name = "raytracer"
version = "0.1.0"
authors = ["Paul Wilson <sf@statusfailed.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.27.1"
rand = "0.3"
